import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]

def list_files(folder: str, suffixes=()):
    p = ROOT / folder
    if not p.exists():
        return []
    out = []
    for f in sorted(p.rglob("*")):
        if f.is_file():
            if suffixes and f.suffix not in suffixes:
                continue
            out.append(str(f.relative_to(ROOT)).replace("\\", "/"))
    return out

def main():
    manifest = {
        "manifest_version": "config/1.0",
        "generated_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "notes": "Generated by scripts/gen_manifest.py",

        # 手書き運用の思想を残すため、requiredは固定（必要ならここを編集）
        "required": {
            "taxonomy/tags.json": "manual",
            "rules/dedupe_policy.json": "manual",
            "rules/blocklist.json": "manual",
            "policies/summarization_policy.md": "manual",
            "policies/publishing_policy.md": "manual",
            "templates/discord_thread.md": "manual",
            "templates/discord_update.md": "manual",
            "templates/discord_rumor_box.md": "manual",
            "prompts/summarizer_user_template.md": "manual",
            "prompts/summarizer_bullet_system.md": "manual",
            "prompts/summarizer_narrative_system.md": "manual",
            "prompts/tagger_system.md": "manual",
            "prompts/translator_system.md": "manual"
        },

        "sources": list_files("sources", suffixes=(".jsonl",)),
        "prompts": list_files("prompts", suffixes=(".md",)),
        "templates": list_files("templates", suffixes=(".md",)),
        "policies": list_files("policies", suffixes=(".md",)),
        "rules": list_files("rules", suffixes=(".json", ".md",))
    }

    (ROOT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("Wrote manifest.json")

if __name__ == "__main__":
    main()
